# Generated by Django 3.1.7 on 2021-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
