# Generated by Django 3.1.7 on 2021-03-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_remove_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authe.adress'),
            preserve_default=False,
        ),
    ]
